version: '3.9'

services:
  db:
    image: postgres:14
    container_name: cityx_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  etl:
    build: ./etl
    container_name: cityx_etl
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./data:/app/data
    environment:
      - DB_HOST=db
    command: ["python", "etl.py"]

volumes:
  postgres_data:
